package org.agoncal.quarkus.microservices.book;

import jakarta.ws.rs.ApplicationPath;
import jakarta.ws.rs.core.Application;
import org.eclipse.microprofile.openapi.annotations.ExternalDocumentation;
import org.eclipse.microprofile.openapi.annotations.OpenAPIDefinition;
import org.eclipse.microprofile.openapi.annotations.info.Contact;
import org.eclipse.microprofile.openapi.annotations.info.Info;
import org.eclipse.microprofile.openapi.annotations.info.License;
import org.eclipse.microprofile.openapi.annotations.tags.Tag;

@ApplicationPath("/")
@OpenAPIDefinition(
        info = @Info(title = "Book Microservice",
                description = "This microservice creates Books with the given title, author, year of publication, genre and ISBN-13 (which will be generated by the number microservice).",
                version = "1.0.0",
                contact = @Contact(name = "Emanuel G.", url = "https://www.linkedin.com/in/emanuel-georgi-0a012a381/")),
        externalDocs = @ExternalDocumentation(url = "https://github.com/GeorgiEmanuel/Quarkus-Microservices", description = "All the microservices code"),
        tags = {
                @Tag(name = "api", description = "Public API that can be used by anybody"),
                @Tag(name = "numbers", description = "Endpoints related to numbers")
        }

)
public class BookMicroservice extends Application {
}

